# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir B:/Projects/Vivado/project_lab_3/tmp/project_lab_3.cache/wt [current_project]
set_property parent.project_path B:/Projects/Vivado/project_lab_3/tmp/project_lab_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo b:/Projects/Vivado/project_lab_3/tmp/project_lab_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  B:/Projects/Vivado/project_lab_3/rtl/button_synchronizer.v
  B:/Projects/Vivado/project_lab_3/rtl/counter_4.v
  B:/Projects/Vivado/project_lab_3/rtl/counter_array.v
  B:/Projects/Vivado/project_lab_3/rtl/decoder_4.v
  B:/Projects/Vivado/project_lab_3/rtl/key_processing.v
  B:/Projects/Vivado/project_lab_3/rtl/mode_selector.v
  B:/Projects/Vivado/project_lab_3/rtl/ms10_timer.v
  B:/Projects/Vivado/project_lab_3/rtl/reset_block.v
  B:/Projects/Vivado/project_lab_3/rtl/stopwatch.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc B:/Projects/Vivado/project_lab_3/xdc/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files B:/Projects/Vivado/project_lab_3/xdc/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top stopwatch -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef stopwatch.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
